version: '3.4'

services:
  lbc.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081
      - KeyVaultName=lbcvault
    ports:
      - "8081"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
