version: '3.4'

services:
  lbc.web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - KeyVaultName=lbcvault
    ports:
      - "8081"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
